[phases.setup]
nixPkgs = ['nodejs', 'bun', 'openssl', 'openssl-dev']

[phases.install]
cmds = ['bun install']

[phases.build]
cmds = ['bunx prisma generate', 'bun run build']

[start]
cmd = 'bunx prisma db push --accept-data-loss && bun run start'
